# Generated by Django 4.0 on 2022-02-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infratores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('setor', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Infrator',
                'verbose_name_plural': 'Infratores',
            },
        ),
    ]
