# Generated by Django 4.0 on 2022-02-20 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infratores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfracoesTipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('vibs', models.IntegerField(default=1, verbose_name='VIBS(valor por infração de boca suja)')),
                ('multiplicador_vibs', models.IntegerField(default=1, verbose_name='multiplicador do VIBS(1VIBS = 1R$)')),
            ],
            options={
                'verbose_name': 'Tipo de Infração',
                'verbose_name_plural': 'Tipos de Infrações',
            },
        ),
        migrations.CreateModel(
            name='Infracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paga', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infracoes', to='infratores.infratores')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='infracoes', to='infracoes.infracoestipos')),
            ],
            options={
                'verbose_name': 'Infração',
                'verbose_name_plural': 'Infrações',
            },
        ),
    ]
