# Generated by Django 4.0 on 2022-02-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfracoesTipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('vibs', models.IntegerField(default=1, verbose_name='VIBS(valor por infração de boca suja)')),
                ('multiplicador_vibs', models.IntegerField(default=1, verbose_name='multiplicador do VIBS(1VIBS = 1R$)')),
            ],
        ),
        migrations.CreateModel(
            name='Infracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paga', models.BooleanField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='infracoes.infracoestipos')),
            ],
        ),
    ]
