# Generated by Django 4.0 on 2022-02-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('infracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infracoes',
            options={'verbose_name': 'Infração', 'verbose_name_plural': 'Infrações'},
        ),
        migrations.AlterModelOptions(
            name='infracoestipos',
            options={'verbose_name': 'Tipo de Infração', 'verbose_name_plural': 'Tipos de Infrações'},
        ),
        migrations.AlterField(
            model_name='infracoes',
            name='paga',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='infracoes',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infracoes', to='pessoas.pessoa'),
        ),
        migrations.AlterField(
            model_name='infracoes',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='infracoes', to='infracoes.infracoestipos'),
        ),
    ]
